"""Mako template for Alembic revisions."""
# Initial schema optimized

revision = 'd8bae116f993'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ark_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ark', sa.String(length=255), nullable=False),
    sa.Column('naan', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=1), nullable=False),
    sa.Column('authority_id', sa.String(length=255), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('metadata_cid', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('alternate_identifiers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tombstoned_at', sa.DateTime(), nullable=True),
    sa.Column('client_item_id', sa.String(length=100), nullable=True),
    sa.Column('publish_retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('publish_last_error', sa.Text(), nullable=True),
    sa.Column('publish_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('publish_permanently_failed', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ark_records_ark'), 'ark_records', ['ark'], unique=True)
    op.create_index(op.f('ix_ark_records_authority_id'), 'ark_records', ['authority_id'], unique=False)
    op.create_index(op.f('ix_ark_records_created_at'), 'ark_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ark_records_state'), 'ark_records', ['state'], unique=False)
    op.create_index('ix_state_authority', 'ark_records', ['state', 'authority_id'], unique=False)
    op.create_index('ix_state_permanently_failed_created', 'ark_records', ['state', 'publish_permanently_failed', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_permanently_failed_created', table_name='ark_records')
    op.drop_index('ix_state_authority', table_name='ark_records')
    op.drop_index(op.f('ix_ark_records_state'), table_name='ark_records')
    op.drop_index(op.f('ix_ark_records_created_at'), table_name='ark_records')
    op.drop_index(op.f('ix_ark_records_authority_id'), table_name='ark_records')
    op.drop_index(op.f('ix_ark_records_ark'), table_name='ark_records')
    op.drop_table('ark_records')
    # ### end Alembic commands ###
